name: 'Close and Release Nexus Staged Repo'
description: 'Closes and releases a staged repo, with a given ID, on https://oss.sonatype.org/.'
inputs:
  username: 
    description: 'Your Sonatype username, same the Sonatype Jira one.'
    required: true
  password: 
    description: 'Your Sonatype password, same the Sonatype Jira one.'
    required: true
  staging_repository_id: 
    description: 'The ID of the staged repository to close and release.'
    required: true
  base_url: 
    description: 'The url of your nexus repository, defaults to OSSRH (https://oss.sonatype.org/service/local/)'
    default: 'https://oss.sonatype.org/service/local/'
  close_only: 
    description: 'This option disable the auto-release process, you will have to do it manually on https://oss.sonatype.org/.'
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
